"""
Generate the evaluation variant of the baseline IDF.

Two reasons this exists:

1. The stock model runs a full year - 35,616 zone timesteps. At ~2 s per
   LLM decision that is roughly 20 hours of wall clock for a single AI
   run, which is not a usable iteration loop.
2. The brief requires the baseline building file *and* the modified
   versions produced during evaluation (deliverable #2). This is that
   modification, generated by script so it is reproducible rather than
   hand-edited.

Two changes are applied, both stated here rather than buried:

A. **RunPeriod narrowed to 1-7 January.** A January week is chosen
   deliberately: Chicago in winter is heating-dominated, so setpoint
   decisions actually move energy. A shoulder-season week would show
   almost no HVAC activity and prove nothing.

B. **Boiler fuel switched from NaturalGas to Electricity.** This is a
   modelling decision, not a tuning knob, and it is load-bearing for the
   whole experiment. `grid.py` supplies a time-of-use tariff and a
   time-varying grid carbon intensity, and both are *electricity*
   signals. With a gas boiler, the heat the controller actually commands
   is billed at a flat rate with a flat emissions factor, so shifting
   heating in time cannot change cost or carbon by construction - the
   agent's core strategy would be unmeasurable no matter how well it
   worked. Electrifying the heat makes every kWh the controller moves
   subject to the same price and carbon signal it is reasoning about.
   It is also the realistic decarbonisation case for this building.

   Note this changes the *magnitude* of reported energy (a 0.8-efficiency
   electric boiler draws site electricity where it previously drew gas),
   but it applies identically to all three arms - native, baseline, and
   ai - so every comparison between them remains like-for-like. Boiler
   efficiency is deliberately left untouched at 0.8 so that this script
   changes exactly one field.
"""

from __future__ import annotations

import re
import sys

SRC = "models/baseline.idf"
DST = "models/baseline_week.idf"


def main(src: str = SRC, dst: str = DST) -> None:
    with open(src, encoding="utf-8", errors="replace") as f:
        text = f.read()

    # Narrow RunPeriod to 1-7 January. The fields are positional and
    # comment-annotated, so rewrite them by their trailing labels rather
    # than by offset.
    def shrink(match: re.Match) -> str:
        block = match.group(0)
        block = re.sub(r"(\n\s*)\d+(,\s*!- End Month)", r"\g<1>1\g<2>", block)
        block = re.sub(r"(\n\s*)\d+(,\s*!- End Day of Month)", r"\g<1>7\g<2>", block)
        return block

    new_text, n = re.subn(r"RunPeriod,.*?;", shrink, text, flags=re.S)
    if n == 0:
        sys.exit(f"No RunPeriod object found in {src}")

    # Electrify the boiler - see reason B in the module docstring. Scoped
    # to the Boiler:HotWater block and to the field carrying the "Fuel
    # Type" comment, so it cannot silently rewrite a fuel type somewhere
    # else in the file.
    def electrify(match: re.Match) -> str:
        return re.sub(
            r"(\n\s*)NaturalGas(,\s*!- Fuel Type)", r"\g<1>Electricity\g<2>",
            match.group(0),
        )

    new_text, n_fuel = re.subn(r"Boiler:HotWater,.*?;", electrify, new_text, flags=re.S)
    if n_fuel == 0:
        sys.exit(f"No Boiler:HotWater object found in {src}")
    if "Electricity,              !- Fuel Type" not in new_text:
        sys.exit("Boiler fuel type was not rewritten - check the field comment format")

    with open(dst, "w", encoding="utf-8") as f:
        f.write(new_text)

    period = re.search(r"RunPeriod,.*?;", new_text, flags=re.S).group(0)
    print(f"Wrote {dst}\n")
    print("\n".join(line.rstrip() for line in period.splitlines()[:8]))
    print("\nBoiler fuel type -> Electricity (see module docstring, reason B)")


if __name__ == "__main__":
    main()
